version: '2'
 
services:
  db:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql
  app:
    build:
      context:  ./BodaBodaServer
      dockerfile: Dockerfile
    expose:
      - "5000"
    depends_on:
      - db
    links:
      - db
 
  proxy:
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
    links:
      - app
